/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    EventCard: typeof import('./src/components/events/EventCard.vue')['default']
    EventsList: typeof import('./src/components/events/EventsList.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    TeamsList: typeof import('./src/components/teams/TeamsList.vue')['default']
  }
}
